services:
  prestashop:
    image: prestashop/prestashop:1.7.8
    platform: linux/amd64
    volumes:
      - ./prestashop:/var/www/html
      - ./prestashop/modules:/var/www/html/modules
      - ./prestashop/themes:/var/www/html/themes
      - ./prestashop/override:/var/www/html/override
    ports:
      - "8001:80"
      - "8002:443"
    environment:
      PS_INSTALL_AUTO: ${PS_INSTALL_AUTO:-0}
      DB_PASSWD: ${DB_PASSWD:-admin}
      DB_NAME: ${DB_NAME:-wloczki-warmii}
      DB_SERVER: ${DB_SERVER:-db}
      DB_PREFIX: ${DB_PREFIX:-ps_wloczki_}
      PS_DOMAIN: ${PS_DOMAIN:-localhost:8001}
      PS_INSTALL_DB: ${PS_INSTALL_DB:-1}
      PS_FOLDER_INSTALL: ${PS_FOLDER_INSTALL:-install-dev}
      PS_FOLDER_ADMIN: ${PS_FOLDER_ADMIN:-admin-dev}
      PS_COUNTRY: ${PS_COUNTRY:-pl}
      PS_LANGUAGE: ${PS_LANGUAGE:-pl}
      PS_DEV_MODE: ${PS_DEV_MODE:-0}
      PS_ENABLE_SSL: ${PS_ENABLE_SSL:-0}
      ADMIN_MAIL: ${ADMIN_MAIL:-admin@wloczki.pl}
      ADMIN_PASSWD: ${ADMIN_PASSWD:-123123123}
    networks:
      - shop-network
    depends_on:
      - db

  db:
    image: mysql:8.4
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWD:-admin}
      MYSQL_DATABASE: ${DB_NAME:-wloczki-warmii}
    networks:
      - shop-network

volumes:
  db-data:

networks:
  shop-network:
